package modelo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrador.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class Administrador {
	private String user;
	private String pass;
	public void Operation1() {
	
	}
}
