package modelo;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserverMedioPago.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObserverMedioPago {
	public void NotificarPago(int listaDeRegalos, Date fecha, int usuario, float monto);
}
