package modelo;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObservableMedioPago.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObservableMedioPago {
	public List<IObserverMedioPago> ObserversPago = null;
	public void Attach(IObserverMedioPago o);
	public void Deattach(IObserverMedioPago o);
	public void Notificar();
}
