package modelo;
import java.util.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ListaDeRegalos.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class ListaDeRegalos implements IObservableMails, IObserverCalendario {
	private int codigo;
	private String nombreAgasajado;
	private Date fechaAgasajo;
	private String mailAgasajado;
	private float montoRecaudado;
	private Date fechaInicio;
	private Date fechaFin;
	private String estado;
	private List<ParticipanteLista> participantes;
	private Usuario administrador;
	private float montoARecaudarXIntegrante;
	public void CrearNuevoPago(Date fecha, Usuario u, float monto) {
	
	}
	
	public List<ParticipanteLista> GetParticipantesImpagos() {
		return null;
	}
	
	public List<ParticipanteLista> GetParticipantes() {
		return null;
	}
	
	private ParticipanteLista GetParticipante(Usuario u) {
		return null;
	}
	
	private void ActualizarMontoRecaudado(float monto) {
	
	}
	
	public void SetEstado(String estado) {
	
	}
	
	public void BajarParticipanteLista(Usuario u) {
	
	}
	
	public void AgregarParticipanteLista(Usuario ul) {
	
	}

	@Override
	public void ModificarEstado() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void Attach(IObserverMail o) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void Deattach(IObserverMail o) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void SendMails() {
		// TODO Auto-generated method stub
		
	}
}
