package modelo;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pago.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class Pago {
	private float monto;
	private Date fecha;
	public float GetMonto() {
		return 0;
	}
}
