package modelo;
import java.util.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ParticipanteLista.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class ParticipanteLista {
	private Usuario usuario;
	private boolean pago;
	private String estado;
	public List<Pago> GetPagos() {
		return null;
	}
	
	public void SetPago(boolean p) {
	
	}
	
	public void SetEstado(String e) {
		
	}
	
	public void CrearNuevoPago(Date fecha, float monto) {
	
	}
}
