package modelo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class Usuario {
	private int codigo;
	private String user;
	private String pass;
	private String nombre;
	private String apellido;
	private int DNI;
	private String mail;
	public String GetMail() {
		return null;
	}
}
