import java.util.List;

import modelo.IObserverMail;
import modelo.ListaDeRegalos;
import modelo.ParticipanteLista;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DESPACHADORMAILS.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class DESPACHADORMAILS implements IObserverMail {

	@Override
	public void SendMailFinalizo(ListaDeRegalos l) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void SendMailsIniciol(List<ParticipanteLista> p) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void SendMailsProximoFinalizarl(List<ParticipanteLista> p) {
		// TODO Auto-generated method stub
		
	}
}
