package modelo;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObservableMails.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObservableMails {
	public List<IObserverMail> observers = null;
	public void Attach(IObserverMail o);
	public void Deattach(IObserverMail o);
	public void SendMails();
}
