package modelo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserverProximoFinalizar.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObserverProximoFinalizar {
	public void SendMailProximarFinalizacion(ListaDeRegalos l);
}
