package modelo;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObservableCalendario.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObservableCalendario {
	public List<IObserverCalendario> observersCalendario=null;
	public void Attach(IObserverCalendario o);
	
	public void Deattach(IObserverCalendario o);
	
	public void NotifyAll();
}
