package modelo;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserverMail.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObserverMail {
	public void SendMailFinalizo(ListaDeRegalos l);
	public void SendMailsIniciol(List<ParticipanteLista> p);
	public void SendMailsProximoFinalizarl(List<ParticipanteLista> p);
}
