import modelo.IObservableCalendario;
import modelo.IObserverCalendario;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Calendar.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class Calendar implements IObservableCalendario {

	@Override
	public void Attach(IObserverCalendario o) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void Deattach(IObserverCalendario o) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void NotifyAll() {
		// TODO Auto-generated method stub
		
	}
}
