import modelo.IObservableMedioPago;
import modelo.IObserverMedioPago;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TARJETACREDITO.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class TARJETACREDITO implements IObservableMedioPago {

	@Override
	public void Attach(IObserverMedioPago o) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void Deattach(IObserverMedioPago o) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void Notificar() {
		// TODO Auto-generated method stub
		
	}
}
