import java.util.Date;

import modelo.ListaDeRegalos;
import modelo.Usuario;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FacadeMobil.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class FacadeMobil {
	public void NuevoPago(int listaDeRegalos, Date fecha, int usuario, float monto) {
	
	}
	
	public ListaDeRegalos GetListaRegalos(int l) {
		return null;
	}
	
	public Usuario GetUsuario(int u) {
		return null;
	}
}
