import java.awt.EventQueue;

import vista.Login;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SistemaRegalos.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class SistemaRegalos {
	public SistemaRegalos sistemaRegalos;
	public int diasProximoAVencer;
	public boolean Login(String user, String pass) {
		return false;
	}
	
	public SistemaRegalos GetInstance() {
		return this.sistemaRegalos;
	}
	
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Login frame = new Login();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
}
