//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SistemaRegalos.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class SistemaRegalos {
	public SistemaRegalos sistemaRegalos;
	public int diasProximoAVencer;
	public boolean Login(String user, String pass) {
		return false;
	}
	
	public SistemaRegalos GetInstance() {
		return this.sistemaRegalos;
	}
}
