package modelo;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserverCalendario.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public interface IObserverCalendario {
	public void ModificarEstado();
}
