package controlador;
import java.util.List;

import modelo.ListaDeRegalos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorListaRegalos.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//

public class ControladorListaRegalos {
	public ControladorListaRegalos controladorListaRegalos;
	public ListaDeRegalos GetListaRegalos(int l) {
		return null;
	}
	
	public ControladorListaRegalos GetInstance() {
		return this.controladorListaRegalos;
	}
	
	public void VerificarEstadoListas(int dias) {
		
	}
	
	public List<ListaDeRegalos> GetListasDelParticipante(int u) {
		return null;
	}
	
	public void BajarParticipanteLista(int usuario, int codigoLista) {
	
	}
	
	public void AgregarParticipanteLista(int usuario, int codigoLista) {
	
	}
}
