package controlador;
import java.util.Date;

import modelo.IObserverMedioPago;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorPagos.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class ControladorPagos implements IObserverMedioPago {
	public ControladorPagos controladorPagos;
	public ControladorPagos GetInstance() {
		return this.controladorPagos;
	}
	@Override
	public void NotiicarPago(int listaDeRegalos, Date fecha, int usuario, float monto) {
		// TODO Auto-generated method stub
		
	}
}
