package controlador;
import java.util.List;

import modelo.Administrador;
import modelo.Usuario;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorUsuario.java
//  @ Date : 19/05/2018
//  @ Author : 
//
//




public class ControladorUsuario {
	public static ControladorUsuario controladorUsuario;
	private List<Usuario> usuarios;
	private List<Administrador> administradores;

	private ControladorUsuario() {
		
	}
	
	public Usuario GetUsuario(int u) {
		return null;
	}
	
	public List<Usuario> GetUsuarios(){
		return this.usuarios;
	}
	
	public List<Administrador> GetAdministradores(){
		return this.administradores;
	}
	
	public ControladorUsuario GetInstance() {
		return this.controladorUsuario;
	}
}
